# Tensor Manipulation

In [ ]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [169]:
# tensorflow version:
print('tensorflow version:{0}'.format(tf.__version__))
print('tensorflow version:%s' % tf.__version__)

tensorflow version:1.2.0
tensorflow version:1.2.0


In [170]:
# numpy version:
print('numpy version:{0}'.format(np.__version__))
print('numpy version:%s' % np.__version__)

numpy version:1.13.0
numpy version:1.13.0


## Simple Array

In [171]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

pp.pprint(t)
print(t.ndim) # rank

# t.shape는 튜플로 반환
# 1차원 배열이라도 다차원 배열일 때와 통일된 형태로 결과를 반환하기 위함
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


# 2D Array

In [172]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


## Shape, Rank, Axis

In [173]:
t = tf.constant([1,2,3,4])

print('t : \n {0}'.format(tf.shape(t).eval()))
tf.shape(t).eval()

t : 
 [4]


array([4], dtype=int32)

In [174]:
t = tf.constant([[1,2],
                 [3,4]])

print('t : \n {0}'.format(tf.shape(t).eval()))
tf.shape(t).eval()

t : 
 [2 2]


array([2, 2], dtype=int32)

In [175]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])

print('t : \n {0}'.format(tf.shape(t).eval()))
tf.shape(t).eval()

t : 
 [1 2 3 4]


array([1, 2, 3, 4], dtype=int32)

In [176]:
t = [
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

pp.pprint(t)
print('t : \n {0}'.format(tf.rank(t).eval()))
print('t : \n {0}'.format(tf.shape(t).eval()))

[   [   [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]
t : 
 4
t : 
 [1 2 3 4]


## Matmul VS multiply

In [177]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[ 12.]], dtype=float32)

In [178]:
(matrix1*matrix2).eval()

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

## Watch out broadcasting

In [179]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print('matrix1 : \n {0}'.format(matrix1.eval()))
print('matrix2 : \n {0}'.format(matrix2.eval()))
print('matrix1+matrix2 : \n {0}'.format((matrix1+matrix2).eval()))
(matrix1+matrix2).eval()

matrix1 : 
 [[ 3.  3.]]
matrix2 : 
 [[ 2.]
 [ 2.]]
matrix1+matrix2 : 
 [[ 5.  5.]
 [ 5.  5.]]


array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [180]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

## Random values for variable initializations 

In [181]:
tf.random_normal([3]).eval()

array([ 0.45671603, -0.85167176, -1.58440542], dtype=float32)

In [182]:
tf.random_uniform([2]).eval()

array([ 0.52622795,  0.80072713], dtype=float32)

In [183]:
tf.random_uniform([2, 3]).eval()

array([[ 0.16610169,  0.40050089,  0.46731901],
       [ 0.68413329,  0.01460004,  0.55141699]], dtype=float32)

## [ Reduce Mean/Sum ]

In [184]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [185]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval()

2.5

In [186]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [187]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [188]:
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

In [189]:
x = [[1., 2.],
     [3., 4.]]

In [190]:
tf.reduce_sum(x).eval()

10.0

In [191]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [192]:
tf.reduce_sum(x, axis=1).eval()

array([ 3.,  7.], dtype=float32)

In [193]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [194]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis

In [195]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [196]:
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [197]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [198]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

## Reshape, squeeze, expand_dims

In [199]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])

pp.pprint(t)
print('t : \n {0}'.format(t))

print('t_dimension : \n {0}'.format(np.ndim(t)))
print('t_shape : \n {0}'.format(np.shape(t)))
print('t_shape : \n {0}'.format(t.shape))

print('t_type : \n {0}'.format(type(t)))
print('t_dtype : \n {0}'.format(t.dtype))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
t : 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
t_dimension : 
 3
t_shape : 
 (2, 2, 3)
t_shape : 
 (2, 2, 3)
t_type : 
 <class 'numpy.ndarray'>
t_dtype : 
 int64


In [200]:
t.shape

(2, 2, 3)

In [201]:
tt = tf.reshape(t, shape=[-1, 3]).eval()

pp.pprint(tt)
print('tt_shape : \n {0}'.format(tt.shape))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
tt_shape : 
 (4, 3)


In [202]:
tt = tf.reshape(t, shape=[-1, 1, 3]).eval()

pp.pprint(tt)
print('tt_shape : \n {0}'.format(tt.shape))

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])
tt_shape : 
 (4, 1, 3)


In [203]:
tt = tf.squeeze([[0], [1], [2]]).eval()

pp.pprint(tt)
print('tt_shape : \n {0}'.format(tt.shape))
print('tt_shape : \n {0}'.format(tt.shape[0]))

array([0, 1, 2], dtype=int32)
tt_shape : 
 (3,)
tt_shape : 
 3


In [204]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

## [ One hot ] 

In [205]:
tt = np.array([[0], [1], [2], [0]])
tt_one_hot = tf.one_hot(tt, depth=3).eval()

# pp.pprint(tt)
print('tt : \n {0}'.format(tt))
print('tt_shape : \n {0}'.format(tt.shape))

# pp.pprint(tt_one_hot)
print('tt_one_hot : \n {0}'.format(tt_one_hot))
print('tt_one_hot_shape : \n {0}'.format(tt_one_hot.shape))

tt : 
 [[0]
 [1]
 [2]
 [0]]
tt_shape : 
 (4, 1)
tt_one_hot : 
 [[[ 1.  0.  0.]]

 [[ 0.  1.  0.]]

 [[ 0.  0.  1.]]

 [[ 1.  0.  0.]]]
tt_one_hot_shape : 
 (4, 1, 3)


In [206]:
tt = np.array([[0], [1], [2], [0]])
tt_one_hot = tf.one_hot(tt, depth=4).eval()


# pp.pprint(tt)
print('tt : \n {0}'.format(tt))
print('tt_shape : \n {0}'.format(tt.shape))

# pp.pprint(tt_one_hot)
print('tt_one_hot : \n {0}'.format(tt_one_hot))
print('tt_one_hot_shape : \n {0}'.format(tt_one_hot.shape))

tt : 
 [[0]
 [1]
 [2]
 [0]]
tt_shape : 
 (4, 1)
tt_one_hot : 
 [[[ 1.  0.  0.  0.]]

 [[ 0.  1.  0.  0.]]

 [[ 0.  0.  1.  0.]]

 [[ 1.  0.  0.  0.]]]
tt_one_hot_shape : 
 (4, 1, 4)


In [207]:
tt = np.array([[0], [1], [2], [0]])
tt_one_hot = tf.one_hot(tt, depth=3).eval()
tt_one_hot_reshape = tf.reshape(tt_one_hot, shape=[-1, 3]).eval()


# pp.pprint(tt)
print('tt : \n {0}'.format(tt))
print('tt_shape : \n {0}'.format(tt.shape))

# pp.pprint(tt_one_hot)
print('tt_one_hot : \n {0}'.format(tt_one_hot))
print('tt_one_hot_shape : \n {0}'.format(tt_one_hot.shape))

# pp.pprint(tt_one_hot_reshape)
print('tt_one_hot_reshape : \n {0}'.format(tt_one_hot_reshape))
print('tt_one_hot_reshape_shape : \n {0}'.format(tt_one_hot_reshape.shape))

tt : 
 [[0]
 [1]
 [2]
 [0]]
tt_shape : 
 (4, 1)
tt_one_hot : 
 [[[ 1.  0.  0.]]

 [[ 0.  1.  0.]]

 [[ 0.  0.  1.]]

 [[ 1.  0.  0.]]]
tt_one_hot_shape : 
 (4, 1, 3)
tt_one_hot_reshape : 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]
tt_one_hot_reshape_shape : 
 (4, 3)


## casting

In [208]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [209]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

## Stack

In [210]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [211]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [212]:
tf.stack([x, y, z], axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

## Ones like and Zeros like

In [213]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [214]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

## Zip


In [215]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [216]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [217]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [218]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [219]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [220]:
t2 = tf.transpose(t, [1, 2, 0])

print(dir(t2))
pp.pprint(sess.run(t2).ndim)
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

['OVERLOADABLE_OPERATORS', '__abs__', '__add__', '__and__', '__array_priority__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__invert__', '__iter__', '__le__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_add_consumer', '_as_node_def_input', '_as_tf_output', '_consumers', '_dtype', '_handle_dtype', '_handle_shape', '_op', '_override_operator', '_shape', '_shape_as_list', '_value_index', 'consumers', 'device', 'dtype', 

In [221]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

# print('functions on "tf.train" class : \n {0}'.format(dir(tf.train)))
index = 0
for func in dir(tf.train):
    print('[%02d] : %s' %  (index, func))
    index += 1

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
[00] : AdadeltaOptimizer
[01] : AdagradDAOptimizer
[02] : AdagradOptimizer
[03] : AdamOptimizer
[04] : BytesList
[05] : CheckpointSaverHook
[06] : CheckpointSaverListener
[07] : ChiefSessionCreator
[08] : ClusterDef
[09] : ClusterSpec
[10] : Coordinator
[11] : Example
[12] : ExponentialMovingAverage
[13] : Feature
[14] : FeatureList
[15] : FeatureLists
[16] : Features
[17] : FeedFnHook
[18] : FinalOpsHook
[19] : FloatList
[20] : FtrlOptimizer
[21] : GlobalStepWaiterHook
[22] : GradientDescentOptimizer
[23] : Int64List
[24] : JobDef
[25] : LoggingTensorHook
[26] : LooperThread
[27] : MomentumOptimizer
[28] : MonitoredSession
[29] : MonitoredTrainingSession
[30] : NanLossDuringTrainingError
[31] : NanTensorHook
[32] : NewCheckpointReader
[33] : Optimizer
[34] : ProximalAdagradOptimizer
[35] : ProximalGradientDescentOptimizer
[36] : QueueRunner
[37] : RMSPropOptimizer
[38] : Saver
[39] : 